name: rmw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # for state management
  flutter_riverpod: ^2.6.1
  # to make http calls
  dio: ^5.9.0
  # to store the jwt securely
  flutter_secure_storage: ^9.2.4

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
          weight: 700
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
          weight: 400
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
          weight: 700
